import Head from 'next/head'
import React from "react";
import NavBar from '../../components/navbar'
import { useRouter } from 'next/router';
import Lottie from "lottie-react";
import lol from "../../public/lol.json";
import { useSession, signIn, signOut } from "next-auth/react";
import { getServerSession } from "next-auth";
import { authOptions } from './api/auth/[...nextauth]'
import PunCard from '../../components/puns';

export default function Home() {

  const router = useRouter();

  const { data: session } = useSession()

  return (
    <>
      <Head>
        <title>OnlyPuns</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/onlypuns.png" />
      </Head>
      <main>
        <NavBar />
        <div className="flex flex-col items-center justify-center min-h-screen max-w-screen py-4 pt-24 my-4">
          <div className="flex flex-col items-center justify-center min-h-full w-6/12 py-2">
            {/* create an array of puns and map through them */}
            {
                Array(20).fill(<PunCard />)
            }
          </div>
        </div>
      </main>
    </>
  )
}

export async function getServerSideProps(context) {
  const session = await getServerSession(context.req, context.res, authOptions)

  if (!session) {
    //redirect to login page
    return {
      redirect: {
        destination: "/",
        permanent: false,
      },
    }
  }

  return {
    props: {
      session,
    },
  }
}