import Head from 'next/head'
import React from "react";
import NavBar from '../../components/navbar'
import { useRouter } from 'next/router';
import Lottie from "lottie-react";
import lol from "../../public/lol.json";
import { useSession, signIn, signOut } from "next-auth/react";
import { getServerSession } from "next-auth";
import { authOptions } from './api/auth/[...nextauth]'

export default function LandingPage() {

  const router = useRouter();

  const { data: session } = useSession()

  return (
    <>
      <Head>
        <title>OnlyPuns</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/onlypuns.png" />
      </Head>
      <main>
        <NavBar />
        <div className="flex flex-col items-center justify-center min-h-full max-w-screen py-2">
          <div className="flex flex-row items-center justify-center min-h-full py-2">
            <Lottie animationData={lol} loop={true} />
            <div>
              <h1 className="text-6xl font-bold">OnlyPuns</h1>
              <h2 className="text-2xl font-bold">The only place for puns</h2>
              <button className='bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded m-2' onClick={() => router.push('/api/auth/signin')}> Get Started </button>
            </div>
          </div>
        </div>
      </main>
    </>
  )
}

export async function getServerSideProps(context) {
  const session = await getServerSession(context.req, context.res, authOptions)

  if (session) {
    //redirect to login page
    return {
      redirect: {
        destination: "/puns",
        permanent: false,
      },
    }
  }

  return {
    props: {
      session,
    },
  }
}