import React from "react";
import Head from "next/head";
import NavBar from "../../../components/navbar";
import AddPost from "../../../components/addpost";
import PunCard from "../../../components/puns";
import { getServerSession } from "next-auth";
import { authOptions } from "../api/auth/[...nextauth]";

export default function Puns({ pun }) {

    console.log(pun.author.image)

    return (
        <>
            <Head>
                <title>OnlyPuns</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/onlypuns.png" />
            </Head>
            <main>
            <NavBar />
            <div className="flex flex-col items-center justify-center min-h-screen max-w-screen py-4 pt-24 my-4">
                <AddPost />
                <div className="flex flex-col items-center justify-center min-h-full w-6/12 py-2">
             
                        <PunCard 
                            key={pun.id} 
                            pun={pun} 
                        />
        
                </div>
            </div>
            </main>
        </>
    );
}

export async function getServerSideProps(context) {

    const session = await getServerSession(context.req, context.res, authOptions)

    const postId = context.query.postId;
   
    const post = await prisma.post.findUnique({
        where: {
            id: Number(postId)
        },
        include: {
            tags: true,
            likes: true,
            comments: true,
            author: true,
        }
    })

    if (!session) {
        //redirect to login page
        return {
        redirect: {
            destination: "/",
            permanent: false,
        },
        }
    }

    return {
        props: {
            session,
            pun: JSON.parse(JSON.stringify(post)),
        },
    };
}